/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.Controlador;
/**
 *
 * @author castrorj
 */
public class AddLanguage extends javax.swing.JFrame {

    Controlador controlador = new Controlador();
    /**
     * Creates new form AddLanguage
     */
    public AddLanguage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Title = new javax.swing.JLabel();
        lbl_Language = new javax.swing.JLabel();
        lbl_Icon = new javax.swing.JLabel();
        txt_Language = new javax.swing.JTextField();
        btn_Ico = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Language = new javax.swing.JTable();
        btn_Save = new javax.swing.JButton();
        bnt_Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Title.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lbl_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Title.setText("Add Language Menu");

        lbl_Language.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        lbl_Language.setText("Language");

        lbl_Icon.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        lbl_Icon.setText("Icon");

        txt_Language.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N

        btn_Ico.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        btn_Ico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
        btn_Ico.setText("Add");

        tbl_Language.setFont(new java.awt.Font("Avenir Next Condensed", 0, 12)); // NOI18N
        tbl_Language.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Forgot_your_password", ""},
                {"Add", null},
                {"Remove", null},
                {"Add_Language_Menu", null},
                {"Icon", null},
                {"Original_Words", null},
                {"Translation", null},
                {"Remove_language", null},
                {"Language", null},
                {"Administration", null},
                {"Create", null},
                {"Activate", null},
                {"DeActivate", null},
                {"Report", null},
                {"Log_Out", null},
                {"User", null},
                {"Prod_Number", null},
                {"Serial_Number", null},
                {"ReworkType", null},
                {"Remarks", null},
                {"Rework_Menu", null},
                {"Select_a_board_from_the_table_and_press_Select_Board_button", null},
                {"Select_Board", null},
                {"Rework_End_Activity", null},
                {"Initial_Time", null},
                {"Rework_Start_Activity", null},
                {"Prod_No", null},
                {"Serial_No", null},
                {"Owner", null},
                {"Idle_Time", null},
                {"Cancel", null},
                {"Start_Activity", null},
                {"End_Activity", null},
                {"Employee_No", null},
                {"Employee_Number", null},
                {"Business_Unit", null},
                {"Name", null},
                {"Area", null},
                {"Department", null},
                {"Department_No", null},
                {"Employee", null},
                {"Last_Name", null},
                {"Password", null},
                {"Rol", null},
                {"Task_Name", null},
                {"MySQL_Query", null},
                {"Columns", null},
                {"Run_Query", null}
            },
            new String [] {
                "Original Words", "Translation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_Language);

        btn_Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N

        bnt_Cancel.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        bnt_Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/error.png"))); // NOI18N
        bnt_Cancel.setMaximumSize(new java.awt.Dimension(133, 41));
        bnt_Cancel.setMinimumSize(new java.awt.Dimension(133, 41));
        bnt_Cancel.setPreferredSize(new java.awt.Dimension(133, 41));
        bnt_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lbl_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bnt_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(btn_Save))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Language)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbl_Icon)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Language)
                            .addComponent(btn_Ico, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Language)
                    .addComponent(txt_Language, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Icon)
                    .addComponent(btn_Ico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bnt_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btn_Save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnt_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_CancelActionPerformed
        // TODO add your handling code here:
        controlador.BackLogIn(this);
    }//GEN-LAST:event_bnt_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddLanguage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddLanguage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddLanguage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddLanguage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddLanguage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_Cancel;
    private javax.swing.JButton btn_Ico;
    private javax.swing.JButton btn_Save;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Icon;
    private javax.swing.JLabel lbl_Language;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JTable tbl_Language;
    private javax.swing.JTextField txt_Language;
    // End of variables declaration//GEN-END:variables
}
