/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Idiomas.Idioma;
import java.awt.Font;
import Vista.LogIn;
import Controlador.Controlador;
/**
 *
 * @author castrorj
 */
public class Administracion extends javax.swing.JFrame {

    Controlador controlador = new Controlador();
    public void Language (){
        Idioma idiom = new Idioma();
        if (LogIn.lang != "" && LogIn.Country != ""){
            lbl_Title.setText(idiom.language(LogIn.lang, LogIn.Country, "Administration"));
            btn_Create.setText(idiom.language(LogIn.lang, LogIn.Country, "Create"));
            btn_Activate.setText(idiom.language(LogIn.lang, LogIn.Country, "Activate") + " " + idiom.language(LogIn.lang, LogIn.Country, "DeActivate"));
            btn_Report.setText(idiom.language(LogIn.lang, LogIn.Country, "Report"));
            btn_LogOut.setText(idiom.language(LogIn.lang, LogIn.Country, "Log_Out"));
        }
    }
        /**
     * Creates new form Administracion
     */
    public Administracion() {
        initComponents();
        Language();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_Create = new javax.swing.JButton();
        btn_Activate = new javax.swing.JButton();
        btn_Report = new javax.swing.JButton();
        btn_LogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Title.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lbl_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Title.setText("Administration");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_Create.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        btn_Create.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/create-new-pencil-button.png"))); // NOI18N
        btn_Create.setText("Create");
        btn_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CreateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Create);

        btn_Activate.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        btn_Activate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/switches-on-and-off.png"))); // NOI18N
        btn_Activate.setText("Activate Deactivate");
        btn_Activate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActivateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Activate);

        btn_Report.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        btn_Report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/progress-report.png"))); // NOI18N
        btn_Report.setText("Reports");
        btn_Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReportActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Report);

        btn_LogOut.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        btn_LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        btn_LogOut.setText("Log Out");
        btn_LogOut.setMaximumSize(new java.awt.Dimension(113, 41));
        btn_LogOut.setMinimumSize(new java.awt.Dimension(113, 41));
        btn_LogOut.setPreferredSize(new java.awt.Dimension(113, 41));
        btn_LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_LogOut);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CreateActionPerformed
        // TODO add your handling code here:
        Create create = new Create();
        create.setLocationRelativeTo(null);
        create.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_CreateActionPerformed

    private void btn_ActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActivateActionPerformed
        // TODO add your handling code here:
        DeActivate act = new DeActivate();
        act.setLocationRelativeTo(null);
        act.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ActivateActionPerformed

    private void btn_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogOutActionPerformed
        // TODO add your handling code here:
        controlador.BackLogIn(this);
    }//GEN-LAST:event_btn_LogOutActionPerformed

    private void btn_ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReportActionPerformed
        // TODO add your handling code here:
        Reports report = new Reports();
        report.setLocationRelativeTo(null);
        report.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Administracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Activate;
    private javax.swing.JButton btn_Create;
    private javax.swing.JButton btn_LogOut;
    private javax.swing.JButton btn_Report;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Title;
    // End of variables declaration//GEN-END:variables
}
