/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import Idiomas.Idioma;

/**
 *
 * @author castrorj
 */
public class DeActivate extends javax.swing.JFrame {

    Controlador controlador = new Controlador();
    
    public void Language (){
        Idioma idiom = new Idioma();
        if (LogIn.lang != "" && LogIn.Country != ""){
            lbl_Title.setText(idiom.language(LogIn.lang, LogIn.Country, "Create"));
            lbl_BU.setText(idiom.language(LogIn.lang, LogIn.Country, "Name"));
        }
    }
    /**
     * Creates new form Create
     */
    public DeActivate() {
        initComponents();
        Language();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Active = new javax.swing.ButtonGroup();
        lbl_Title = new javax.swing.JLabel();
        btn_Save = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lbl_BU = new javax.swing.JLabel();
        cmb_BU = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        lbl_BU_Area = new javax.swing.JLabel();
        cmb_BU_Area = new javax.swing.JComboBox<>();
        lbl_Area = new javax.swing.JLabel();
        cmb_Area = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        lbl_BU_Dept = new javax.swing.JLabel();
        lbl_Area_Dept = new javax.swing.JLabel();
        lbl_DeptNo = new javax.swing.JLabel();
        cmb_Area_Dept = new javax.swing.JComboBox<>();
        cmb_BU_Dept = new javax.swing.JComboBox<>();
        cmb_Dept = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        lbl_BU_Prod = new javax.swing.JLabel();
        cmb_BU_Prod = new javax.swing.JComboBox<>();
        cmb_Area_Prod = new javax.swing.JComboBox<>();
        lbl_Area_Prod = new javax.swing.JLabel();
        lbl_Dept_Prod = new javax.swing.JLabel();
        cmb_Dept_Prod = new javax.swing.JComboBox<>();
        cmb_Prod_No = new javax.swing.JComboBox<>();
        lbl_Prod_No = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbl_Department_emp = new javax.swing.JLabel();
        cmb_Dept_emp = new javax.swing.JComboBox<>();
        lbl_BU_emp = new javax.swing.JLabel();
        cmb_BU_emp = new javax.swing.JComboBox<>();
        lbl_Area_emp = new javax.swing.JLabel();
        cmb_Area_emp = new javax.swing.JComboBox<>();
        cmb_employee = new javax.swing.JComboBox<>();
        lbl_Employee = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbl_RwkType = new javax.swing.JLabel();
        cmb_Task = new javax.swing.JComboBox<>();
        rdb_Activate = new javax.swing.JRadioButton();
        rdb_DeActivate = new javax.swing.JRadioButton();
        txt_EmpNo = new javax.swing.JTextField();
        lbl_EmpNo = new javax.swing.JLabel();
        btn_Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Title.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lbl_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/switches-on-and-off.png"))); // NOI18N
        lbl_Title.setText("Activate / Deactivate");

        btn_Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N

        jTabbedPane1.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N

        lbl_BU.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        lbl_BU.setText("Business Unit");

        cmb_BU.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        cmb_BU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(lbl_BU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_BU, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_BU)
                    .addComponent(cmb_BU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Business Unit", jPanel1);

        lbl_BU_Area.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        lbl_BU_Area.setText("Business Unit");

        cmb_BU_Area.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        cmb_BU_Area.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_Area.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        lbl_Area.setText("Area");

        cmb_Area.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        cmb_Area.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_Area)
                    .addComponent(lbl_BU_Area))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmb_BU_Area, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_Area, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(149, 149, 149))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_BU_Area)
                    .addComponent(cmb_BU_Area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Area)
                    .addComponent(cmb_Area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Area", jPanel2);

        lbl_BU_Dept.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        lbl_BU_Dept.setText("Business Unit");

        lbl_Area_Dept.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        lbl_Area_Dept.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_Area_Dept.setText("Area");

        lbl_DeptNo.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        lbl_DeptNo.setText("Department No");

        cmb_Area_Dept.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        cmb_Area_Dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmb_BU_Dept.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        cmb_BU_Dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmb_Dept.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        cmb_Dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_DeptNo)
                    .addComponent(lbl_Area_Dept)
                    .addComponent(lbl_BU_Dept))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmb_Area_Dept, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmb_Dept, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmb_BU_Dept, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_BU_Dept)
                    .addComponent(cmb_BU_Dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Area_Dept)
                    .addComponent(cmb_Area_Dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_DeptNo)
                    .addComponent(cmb_Dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Department", jPanel3);

        lbl_BU_Prod.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        lbl_BU_Prod.setText("Business Unit");

        cmb_BU_Prod.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        cmb_BU_Prod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmb_Area_Prod.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        cmb_Area_Prod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_Area_Prod.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        lbl_Area_Prod.setText("Area");

        lbl_Dept_Prod.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        lbl_Dept_Prod.setText("Department");

        cmb_Dept_Prod.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        cmb_Dept_Prod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmb_Prod_No.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        cmb_Prod_No.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_Prod_No.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        lbl_Prod_No.setText("Prod_No");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_Dept_Prod)
                            .addComponent(lbl_Area_Prod)
                            .addComponent(lbl_Prod_No))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmb_Prod_No, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_Dept_Prod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_Area_Prod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbl_BU_Prod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_BU_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(178, 178, 178))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_BU_Prod)
                    .addComponent(cmb_BU_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Area_Prod)
                    .addComponent(cmb_Area_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_Dept_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Dept_Prod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_Prod_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Prod_No))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Prod Number", jPanel4);

        lbl_Department_emp.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        lbl_Department_emp.setText("Department");

        cmb_Dept_emp.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        cmb_Dept_emp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_BU_emp.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        lbl_BU_emp.setText("Business Unit");

        cmb_BU_emp.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        cmb_BU_emp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_Area_emp.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        lbl_Area_emp.setText("Area");

        cmb_Area_emp.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        cmb_Area_emp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmb_employee.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        cmb_employee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_Employee.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        lbl_Employee.setText("Employee");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbl_Area_emp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_Area_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbl_BU_emp)
                        .addGap(12, 12, 12)
                        .addComponent(cmb_BU_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbl_Employee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbl_Department_emp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_Dept_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(165, 165, 165))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_BU_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbl_BU_emp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_Area_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Area_emp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_Dept_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Department_emp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_employee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Employee))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Employee", jPanel5);

        lbl_RwkType.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        lbl_RwkType.setText("Task Name");

        cmb_Task.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(lbl_RwkType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmb_Task, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_RwkType)
                    .addComponent(cmb_Task, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ReworkType", jPanel6);

        Active.add(rdb_Activate);
        rdb_Activate.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        rdb_Activate.setText("Activate");

        Active.add(rdb_DeActivate);
        rdb_DeActivate.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        rdb_DeActivate.setText("DeActivate");

        txt_EmpNo.setEditable(false);
        txt_EmpNo.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        txt_EmpNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbl_EmpNo.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        lbl_EmpNo.setText("Employee No");

        btn_Cancel.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        btn_Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/error.png"))); // NOI18N
        btn_Cancel.setText("Cancel");
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(lbl_EmpNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_EmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdb_Activate)
                .addGap(47, 47, 47)
                .addComponent(rdb_DeActivate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btn_Cancel)
                .addGap(151, 151, 151)
                .addComponent(btn_Save)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_EmpNo)
                    .addComponent(txt_EmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdb_Activate)
                    .addComponent(rdb_DeActivate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Save)
                    .addComponent(btn_Cancel))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
        // TODO add your handling code here:
        controlador.BackAdministration(this);
    }//GEN-LAST:event_btn_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeActivate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeActivate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeActivate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeActivate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeActivate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Active;
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_Save;
    private javax.swing.JComboBox<String> cmb_Area;
    private javax.swing.JComboBox<String> cmb_Area_Dept;
    private javax.swing.JComboBox<String> cmb_Area_Prod;
    private javax.swing.JComboBox<String> cmb_Area_emp;
    private javax.swing.JComboBox<String> cmb_BU;
    private javax.swing.JComboBox<String> cmb_BU_Area;
    private javax.swing.JComboBox<String> cmb_BU_Dept;
    private javax.swing.JComboBox<String> cmb_BU_Prod;
    private javax.swing.JComboBox<String> cmb_BU_emp;
    private javax.swing.JComboBox<String> cmb_Dept;
    private javax.swing.JComboBox<String> cmb_Dept_Prod;
    private javax.swing.JComboBox<String> cmb_Dept_emp;
    private javax.swing.JComboBox<String> cmb_Prod_No;
    private javax.swing.JComboBox<String> cmb_Task;
    private javax.swing.JComboBox<String> cmb_employee;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_Area;
    private javax.swing.JLabel lbl_Area_Dept;
    private javax.swing.JLabel lbl_Area_Prod;
    private javax.swing.JLabel lbl_Area_emp;
    private javax.swing.JLabel lbl_BU;
    private javax.swing.JLabel lbl_BU_Area;
    private javax.swing.JLabel lbl_BU_Dept;
    private javax.swing.JLabel lbl_BU_Prod;
    private javax.swing.JLabel lbl_BU_emp;
    private javax.swing.JLabel lbl_Department_emp;
    private javax.swing.JLabel lbl_DeptNo;
    private javax.swing.JLabel lbl_Dept_Prod;
    private javax.swing.JLabel lbl_EmpNo;
    private javax.swing.JLabel lbl_Employee;
    private javax.swing.JLabel lbl_Prod_No;
    private javax.swing.JLabel lbl_RwkType;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JRadioButton rdb_Activate;
    private javax.swing.JRadioButton rdb_DeActivate;
    private javax.swing.JTextField txt_EmpNo;
    // End of variables declaration//GEN-END:variables
}
