/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.Controlador;
/**
 *
 * @author castrorj
 */
public class Technician extends javax.swing.JFrame {

    Controlador controlador = new Controlador();
    /**
     * Creates new form Technician
     */
    public Technician() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Title = new javax.swing.JLabel();
        lbl_User = new javax.swing.JLabel();
        txt_User = new javax.swing.JTextField();
        lbl_ProdNo = new javax.swing.JLabel();
        cmb_ProdNo = new javax.swing.JComboBox<>();
        lbl_SerialNo = new javax.swing.JLabel();
        txt_SerialNo = new javax.swing.JTextField();
        lbl_RwkType = new javax.swing.JLabel();
        cmb_RwkType = new javax.swing.JComboBox<>();
        lbl_remarks = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Remarks = new javax.swing.JTextArea();
        btn_Save = new javax.swing.JButton();
        bnt_LogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Title.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lbl_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Title.setText("Technician");

        lbl_User.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        lbl_User.setText("User");

        txt_User.setEditable(false);
        txt_User.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N

        lbl_ProdNo.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        lbl_ProdNo.setText("Prod Number");

        cmb_ProdNo.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        cmb_ProdNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_SerialNo.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        lbl_SerialNo.setText("Serial Number");

        txt_SerialNo.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N

        lbl_RwkType.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        lbl_RwkType.setText("ReworkType");

        cmb_RwkType.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        cmb_RwkType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_remarks.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        lbl_remarks.setText("Remarks");

        txt_Remarks.setColumns(20);
        txt_Remarks.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        txt_Remarks.setRows(5);
        jScrollPane1.setViewportView(txt_Remarks);

        btn_Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N

        bnt_LogOut.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        bnt_LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        bnt_LogOut.setText("Log Out");
        bnt_LogOut.setMaximumSize(new java.awt.Dimension(133, 41));
        bnt_LogOut.setMinimumSize(new java.awt.Dimension(133, 41));
        bnt_LogOut.setPreferredSize(new java.awt.Dimension(133, 41));
        bnt_LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_LogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_Title, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_SerialNo)
                                    .addComponent(lbl_RwkType))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lbl_remarks))
                                    .addComponent(txt_SerialNo)
                                    .addComponent(cmb_RwkType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_ProdNo)
                                    .addComponent(lbl_User))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_User)
                                    .addComponent(cmb_ProdNo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Save)
                        .addGap(28, 28, 28)
                        .addComponent(bnt_LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_User)
                    .addComponent(txt_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ProdNo)
                    .addComponent(cmb_ProdNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SerialNo)
                    .addComponent(txt_SerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_RwkType)
                    .addComponent(cmb_RwkType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(lbl_remarks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Save)
                    .addComponent(bnt_LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnt_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_LogOutActionPerformed
        // TODO add your handling code here:
        controlador.BackLogIn(this);
    }//GEN-LAST:event_bnt_LogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Technician.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Technician.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Technician.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Technician.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Technician().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_LogOut;
    private javax.swing.JButton btn_Save;
    private javax.swing.JComboBox<String> cmb_ProdNo;
    private javax.swing.JComboBox<String> cmb_RwkType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ProdNo;
    private javax.swing.JLabel lbl_RwkType;
    private javax.swing.JLabel lbl_SerialNo;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JLabel lbl_User;
    private javax.swing.JLabel lbl_remarks;
    private javax.swing.JTextArea txt_Remarks;
    private javax.swing.JTextField txt_SerialNo;
    private javax.swing.JTextField txt_User;
    // End of variables declaration//GEN-END:variables
}
